version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

  redis-insight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - '8001:8001'

  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - '8000:8000'

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
    ports:
      - '3306:3306'

